version: '3.1'

services:
    app:
        image: 'nginx:simple-benefits'
        build: '.'
        ports:
            - 3000:80
        environment:
            - API_BASE_URL=http:\/\/localhost:5000\/api
